### ISSUE TITLE
Add strong name to the assembly

### ISSUE THREAD

**Issue by lyubomirr** [Polly-Contrib/Polly.Contrib.WaitAndRetry#25]
**Is your feature request related to a specific problem? Or an existing feature? Please describe.**
My request is related to a warning I get when using the nuget package ina strong named assembly - "Referenced assembly 'Polly.Contrib.WaitAndRetry, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.".
<br/>
**Describe your proposed or preferred solution**:
Sign the assembly.
<br/>
**Describe any alternative options you've considered**:
Create another nuget package with strong name.

**Comment by reisenberger** [comment]
Thanks for pointing this out.  The intention was that this was published strong-named, and the next release will fix this. 

(The preferred policy for Polly packages is to [publish as strong-named only](https://github.com/App-vNext/Polly/issues/442); see that link if interested in the detail.)

**Comment by reisenberger** [comment]
Fixed in #27, released as [v1.1.1](https://www.nuget.org/packages/Polly.Contrib.WaitAndRetry/1.1.1)
