### ISSUE TITLE
No package on nuget?

### ISSUE THREAD

**Issue by hyrmn** [Polly-Contrib/Polly.Contrib.WaitAndRetry#9]
I read (and sort of understood) the genesis of this lib over on Polly #530. I love love that all of that jitter work has found its own home. But, when I click through on the nuget badge to https://www.nuget.org/packages/Polly.Contrib.WaitAndRetry, I get an oops page. Since there's nothing in the search, I assume this package isn't currently published? What is the recommended consumption model?

**Comment by reisenberger** [comment]
@hyrmn @grant-d  This package Polly.Contrib.WaitAndRetry has no how-to-use documentation (#5). I believe we should have minimal documentation describing the overloads/contents/how-to-use in the readme, before releasing.  Can somebody add that?  We'd love to package this up for release then!

@hyrmn  This doesn't include the jitter yet.

**Comment by reisenberger** [comment]
Awesome, @hyrmn ! Thanks for helping the community forward!  And: thanks @grant-d for your original contribution!

**Comment by reisenberger** [comment]
@hyrmn @grant-d I made PR #11 to bring George Polevoy's new jitter formula in to this repo! 🎉 

@hyrmn If you get a mo for the doco on the existing formulae, I can follow on with the doco for the new jitter formula if you like/helpful, as I dove deep on that. Thanks!

**Comment by hyrmn** [comment]
Sorry, I meant to get to this yesterday @reisenberger. I will have a start for you tonight! I'm quite excited to have the jitter stuff

**Comment by reisenberger** [comment]
@hyrmn @grant-d [Polly.Contrib.WaitAndRetry v1.0.0](https://www.nuget.org/packages/Polly.Contrib.WaitAndRetry/1.0.0) has been published to nuget, and will be available for download as soon as nuget has finished indexing it.  Thanks for everything you have contributed.
